# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.paginator:
        class: AppBundle\Services\Paginator
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }
    app.review:
        class: AppBundle\Services\ReviewService   
        arguments: [ @doctrine.orm.entity_manager]
    app.topic:
        class: AppBundle\Services\TopicService   
        arguments: [ @doctrine.orm.entity_manager ]   
    app.criteria:
        class: AppBundle\Services\CriteriaService   
        arguments: [ @doctrine.orm.entity_manager]      
    app.positive:
        class: AppBundle\Services\PositiveAttributeService   
        arguments: [ @doctrine.orm.entity_manager ]  
    app.negative:
        class: AppBundle\Services\NegativeAttributeService   
        arguments: [ @doctrine.orm.entity_manager ]    
    app.score:
        class: AppBundle\Services\ReviewScoreService   
        arguments: [ @doctrine.orm.entity_manager, @app.review ] 
    app.analizeText:
        class: AppBundle\Services\AnalizeTextService           
    app.separator:
        class: AppBundle\Services\SeparatorService   
        arguments: [ @doctrine.orm.entity_manager ]         
